services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maptitecoloc
      MYSQL_USER: coloc
      MYSQL_PASSWORD: coloc
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
volumes:
  mysql-data:
